## Day Objectives:

- Python Data Analysis Packages
    - Numpy
        - Numerical Python
        - Here we can deal with n dimentional arrays.
        - Here arrays are like lists in python.
        - But numpy arrays are faster than lists.
        - we can import this numpy package by using import keyword.
        - axis = 1 means row wise and axis=0 means column wise
    - Pandas
    - Matplotlib
    
    
- Package: Collection of Modules.
    - Module: Collection of or Set of Functions or classes.
    
- Data Science: We can apply statistics on the data so that we can find patterns and solutions.

In [27]:
import numpy as np

In [42]:
arr = np.array([1,2,3,4,5])
print(arr)
type(arr)
arr.ndim

arr.shape

[1 2 3 4 5]


(5,)

In [41]:
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)
type(arr2)
arr2.ndim

arr2.shape

arr2.size

[[1 2 3]
 [4 5 6]]


6

In [43]:
a = [1,2,3,4,5]
tu = (6,7,8,9,10)

x = np.array(a)
y = np.array(tu)

In [44]:
print(x)
print(y)

[1 2 3 4 5]
[ 6  7  8  9 10]


In [82]:
n = np.arange(2,20)
print(n)
len(n)

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


18

In [83]:
r_arr = np.reshape(n,(3,2,3))

In [84]:
print(r_arr)

[[[ 2  3  4]
  [ 5  6  7]]

 [[ 8  9 10]
  [11 12 13]]

 [[14 15 16]
  [17 18 19]]]


In [88]:
ar = np.linspace(5,10,20)

In [89]:
ar

array([ 5.        ,  5.26315789,  5.52631579,  5.78947368,  6.05263158,
        6.31578947,  6.57894737,  6.84210526,  7.10526316,  7.36842105,
        7.63157895,  7.89473684,  8.15789474,  8.42105263,  8.68421053,
        8.94736842,  9.21052632,  9.47368421,  9.73684211, 10.        ])

In [91]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

In [95]:
print("Array a:",a)
print("Array b:",b)

Array a: [[1 2]
 [3 4]]
Array b: [[5 6]
 [7 8]]


In [101]:
# array addition
add = a+b
print(add)

sub = a-b
print(sub)

mul = a*b
print(mul)

div = a/b
print(div)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [102]:
matrix_mul = a@b
print(matrix_mul)

[[19 22]
 [43 50]]


In [103]:
help(np.empty)

Help on built-in function empty in module numpy:

empty(...)
    empty(shape, dtype=float, order='C')
    
    Return a new array of given shape and type, without initializing entries.
    
    Parameters
    ----------
    shape : int or tuple of int
        Shape of the empty array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        Desired output data-type for the array, e.g, `numpy.int8`. Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of uninitialized (arbitrary) data of the given shape, dtype, and
        order.  Object arrays will be initialized to None.
    
    See Also
    --------
    empty_like : Return an empty array with shape and type of input.
    ones : Return a new array setting values to one.
    zeros : Return a new array 

In [109]:
em = np.empty((2,3),dtype=int)
print(em)

[[713563728       326         0]
 [        0         1 538976288]]


In [111]:
ones = np.ones((5,5),dtype=int)
print(ones)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [113]:
zero = np.zeros((4,3))
print(zero)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [117]:
x = ['good ','hi ']
y = ['morning','everyone']
d = np.char.add(x,y)

In [118]:
d

array(['good morning', 'hi everyone'], dtype='<U13')

In [119]:
np.char.title("welcome to the session")

array('Welcome To The Session', dtype='<U22')

In [120]:
np.char.lower('HI SIRI')

array('hi siri', dtype='<U7')

In [143]:
print(arr2)
arr2.T

[[1 2 3]
 [4 5 6]]


array([[1, 4],
       [2, 5],
       [3, 6]])

In [139]:
arr2[:,1]

array([2, 5])

In [ ]:
  0 1 2 
0 1 2 3
1 4 5 6

In [137]:
li = [1,2,3]
li[:]

[1, 2, 3]

In [146]:
x = np.arange(12).reshape((3,4))

In [147]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [149]:
x[2,2]

10

In [150]:
sum(x) # columnwise

array([12, 15, 18, 21])

In [151]:
x.sum(axis = 1) # row wise

array([ 6, 22, 38])

In [155]:
x.max(axis=0) # we will get all the max values in column wise.

array([ 8,  9, 10, 11])

In [156]:
x.min(axis=1) # row wise all minimum numbers\

array([0, 4, 8])

In [159]:
arr  ## 1 3 6 10 15

array([1, 2, 3, 4, 5])

In [161]:
np.cumsum([10,11,1,2,9])

array([10, 21, 22, 24, 33], dtype=int32)

In [162]:
np.cumprod(arr)

array([  1,   2,   6,  24, 120], dtype=int32)